/*
 * Generated by MTK SP DrvGen Version 03.13.6 for MT6589_NP. Copyright MediaTek Inc. (C) 2013.
 * Mon Feb 23 19:01:13 2015
 * Do Not Modify the File.
 */



#include "pmic_drv.h"



//For PMIC driver use


